# Generated by Django 3.2.25 on 2025-05-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True)),
                ('branch', models.CharField(choices=[('select', 'select'), ('cse', 'cse'), ('ece', 'ece'), ('mech', 'mech'), ('eee', 'eee'), ('it', 'it')], max_length=10, null=True)),
            ],
        ),
    ]
