# Generated by Django 3.2.25 on 2025-06-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
