# Generated by Django 3.2.25 on 2025-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_auto_20250619_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(),
        ),
    ]
