# Generated by Django 3.2.25 on 2025-07-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20250619_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='service',
            field=models.CharField(choices=[('Haircut & styling', 'Haircut & styling'), ('facials & skincare', 'facials & skincare'), ('Bridal makeup', 'Bridal makeup')], max_length=50, null=True),
        ),
    ]
