# Generated by Django 3.2.25 on 2025-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_book_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
